version: '3'
services:

  service-c:
    build: ${SERVICE_C:-.}
    command: npm run dev
    ports:
      - "8082:8082"
    volumes:
      - ${SERVICE_C:-.}:/usr/src/app
      - /usr/src/app/node_modules
