version: '3'
services:

  service-node-dev:
    build: ${SERVICE_NODE:-.}
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ${SERVICE_NODE:-.}:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
